#pragma once

#include <cstdint>

// Included by the generated ppc_config.h when PPC_INCLUDE_DETAIL is defined
// (see UnleashedRecompLib/CMakeLists.txt). This file is tracked in git; the
// rest of ppc/ is generated by XenonRecomp and ignored.

struct PPCContext;

// Out-of-line handler for indirect calls whose target is not a recompiled
// function. Logs (rate-limited) and returns, turning a guaranteed wild jump
// into a skipped call. Defined in UnleashedRecomp/kernel/memory.cpp.
extern "C" void PPCIndirectCallMissing(PPCContext& ctx, uint8_t* base, uint32_t target);

// Issue #27: on some devices the game evaluates a half-constructed animation
// subtree; visitors then fetch vtables from guest null (reads absorbed by the
// readable guest null page, see kernel/memory.cpp) and call through method
// pointer 0. The stock macro dereferences the function table unconditionally,
// which for such targets reads far outside the table and jumps to garbage.
// Validate the target range and the resolved host pointer instead of crashing.
// The valid range spans to the image end, not just the code section: kernel import
// thunks live directly after the code (first at exactly PPC_CODE_BASE+PPC_CODE_SIZE)
// and are registered into the function table by Memory::InsertFunction.
#define PPC_CALL_INDIRECT_FUNC(x) \
    do \
    { \
        const uint32_t ppcCallTarget_ = (uint32_t)(x); \
        PPCFunc* ppcCallFn_ = \
            (uint64_t(ppcCallTarget_) - PPC_CODE_BASE < PPC_IMAGE_BASE + PPC_IMAGE_SIZE - PPC_CODE_BASE) \
                ? PPC_LOOKUP_FUNC(base, ppcCallTarget_) \
                : nullptr; \
        if (ppcCallFn_ != nullptr) \
            ppcCallFn_(ctx, base); \
        else \
            PPCIndirectCallMissing(ctx, base, ppcCallTarget_); \
    } while (0)
