github.com:
    users:
        mymes1:
            oauth_token: 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
    git_protocol: https
    user: mymes1
    oauth_token: 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
